# This file is used to set the project main settings

# Give brownie the name of your environment file here it's .env
dotenv: .env

# To allow brownie to connect to your account
wallets:
  from_key: ${PRIVATE_KEY}

# set project dependencies to be downloaded
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"

# set smart contracts addresses for different networks
networks:
  polygon-mumbai:
    matic_price_feed: "0xd0D5e3DB44DE05E9F294BB0a3bEEaF030DE24Ada"
  # alchemy polygon mainnet fork
  polygone-mainnet-dev:
    matic_price_feed: "0xAB594600376Ec9fD91F8e885dADF0CE036862dE0"
  polygon-mainnet:
    matic_price_feed: "0xAB594600376Ec9fD91F8e885dADF0CE036862dE0"
